//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace MVCViews.TeacherService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ITeacherService", Namespace="http://tempuri.org/")]
    public partial class TeacherService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddTeacherInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTeacherInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateTeacherrInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback HasMemberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTeacherInfoListOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveTeacherInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddCommentOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveCommentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCommentByEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetValidFloorOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveTeacherCommentOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TeacherService() {
            this.Url = global::MVCViews.Properties.Settings.Default.MVCViews_TeacherService_TeacherService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddTeacherInfoCompletedEventHandler AddTeacherInfoCompleted;
        
        /// <remarks/>
        public event GetTeacherInfoCompletedEventHandler GetTeacherInfoCompleted;
        
        /// <remarks/>
        public event UpdateTeacherrInfoCompletedEventHandler UpdateTeacherrInfoCompleted;
        
        /// <remarks/>
        public event HasMemberCompletedEventHandler HasMemberCompleted;
        
        /// <remarks/>
        public event GetTeacherInfoListCompletedEventHandler GetTeacherInfoListCompleted;
        
        /// <remarks/>
        public event RemoveTeacherInfoCompletedEventHandler RemoveTeacherInfoCompleted;
        
        /// <remarks/>
        public event AddCommentCompletedEventHandler AddCommentCompleted;
        
        /// <remarks/>
        public event RemoveCommentCompletedEventHandler RemoveCommentCompleted;
        
        /// <remarks/>
        public event GetCommentByEmailCompletedEventHandler GetCommentByEmailCompleted;
        
        /// <remarks/>
        public event GetValidFloorCompletedEventHandler GetValidFloorCompleted;
        
        /// <remarks/>
        public event RemoveTeacherCommentCompletedEventHandler RemoveTeacherCommentCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITeacherService/AddTeacherInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddTeacherInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] TeacherInfoView model, out ReturnState AddTeacherInfoResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool AddTeacherInfoResultSpecified) {
            object[] results = this.Invoke("AddTeacherInfo", new object[] {
                        model});
            AddTeacherInfoResult = ((ReturnState)(results[0]));
            AddTeacherInfoResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void AddTeacherInfoAsync(TeacherInfoView model) {
            this.AddTeacherInfoAsync(model, null);
        }
        
        /// <remarks/>
        public void AddTeacherInfoAsync(TeacherInfoView model, object userState) {
            if ((this.AddTeacherInfoOperationCompleted == null)) {
                this.AddTeacherInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddTeacherInfoOperationCompleted);
            }
            this.InvokeAsync("AddTeacherInfo", new object[] {
                        model}, this.AddTeacherInfoOperationCompleted, userState);
        }
        
        private void OnAddTeacherInfoOperationCompleted(object arg) {
            if ((this.AddTeacherInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddTeacherInfoCompleted(this, new AddTeacherInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITeacherService/GetTeacherInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TeacherInfoView GetTeacherInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email) {
            object[] results = this.Invoke("GetTeacherInfo", new object[] {
                        email});
            return ((TeacherInfoView)(results[0]));
        }
        
        /// <remarks/>
        public void GetTeacherInfoAsync(string email) {
            this.GetTeacherInfoAsync(email, null);
        }
        
        /// <remarks/>
        public void GetTeacherInfoAsync(string email, object userState) {
            if ((this.GetTeacherInfoOperationCompleted == null)) {
                this.GetTeacherInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTeacherInfoOperationCompleted);
            }
            this.InvokeAsync("GetTeacherInfo", new object[] {
                        email}, this.GetTeacherInfoOperationCompleted, userState);
        }
        
        private void OnGetTeacherInfoOperationCompleted(object arg) {
            if ((this.GetTeacherInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTeacherInfoCompleted(this, new GetTeacherInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITeacherService/UpdateTeacherrInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateTeacherrInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] TeacherInfoView model, out ReturnState UpdateTeacherrInfoResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool UpdateTeacherrInfoResultSpecified) {
            object[] results = this.Invoke("UpdateTeacherrInfo", new object[] {
                        model});
            UpdateTeacherrInfoResult = ((ReturnState)(results[0]));
            UpdateTeacherrInfoResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void UpdateTeacherrInfoAsync(TeacherInfoView model) {
            this.UpdateTeacherrInfoAsync(model, null);
        }
        
        /// <remarks/>
        public void UpdateTeacherrInfoAsync(TeacherInfoView model, object userState) {
            if ((this.UpdateTeacherrInfoOperationCompleted == null)) {
                this.UpdateTeacherrInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTeacherrInfoOperationCompleted);
            }
            this.InvokeAsync("UpdateTeacherrInfo", new object[] {
                        model}, this.UpdateTeacherrInfoOperationCompleted, userState);
        }
        
        private void OnUpdateTeacherrInfoOperationCompleted(object arg) {
            if ((this.UpdateTeacherrInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateTeacherrInfoCompleted(this, new UpdateTeacherrInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITeacherService/HasMember", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void HasMember([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email, out bool HasMemberResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool HasMemberResultSpecified) {
            object[] results = this.Invoke("HasMember", new object[] {
                        email});
            HasMemberResult = ((bool)(results[0]));
            HasMemberResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void HasMemberAsync(string email) {
            this.HasMemberAsync(email, null);
        }
        
        /// <remarks/>
        public void HasMemberAsync(string email, object userState) {
            if ((this.HasMemberOperationCompleted == null)) {
                this.HasMemberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHasMemberOperationCompleted);
            }
            this.InvokeAsync("HasMember", new object[] {
                        email}, this.HasMemberOperationCompleted, userState);
        }
        
        private void OnHasMemberOperationCompleted(object arg) {
            if ((this.HasMemberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HasMemberCompleted(this, new HasMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITeacherService/GetTeacherInfoList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Services.cnts")]
        public TeacherInfoView[] GetTeacherInfoList() {
            object[] results = this.Invoke("GetTeacherInfoList", new object[0]);
            return ((TeacherInfoView[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTeacherInfoListAsync() {
            this.GetTeacherInfoListAsync(null);
        }
        
        /// <remarks/>
        public void GetTeacherInfoListAsync(object userState) {
            if ((this.GetTeacherInfoListOperationCompleted == null)) {
                this.GetTeacherInfoListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTeacherInfoListOperationCompleted);
            }
            this.InvokeAsync("GetTeacherInfoList", new object[0], this.GetTeacherInfoListOperationCompleted, userState);
        }
        
        private void OnGetTeacherInfoListOperationCompleted(object arg) {
            if ((this.GetTeacherInfoListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTeacherInfoListCompleted(this, new GetTeacherInfoListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITeacherService/RemoveTeacherInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoveTeacherInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email, out ReturnState RemoveTeacherInfoResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool RemoveTeacherInfoResultSpecified) {
            object[] results = this.Invoke("RemoveTeacherInfo", new object[] {
                        email});
            RemoveTeacherInfoResult = ((ReturnState)(results[0]));
            RemoveTeacherInfoResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void RemoveTeacherInfoAsync(string email) {
            this.RemoveTeacherInfoAsync(email, null);
        }
        
        /// <remarks/>
        public void RemoveTeacherInfoAsync(string email, object userState) {
            if ((this.RemoveTeacherInfoOperationCompleted == null)) {
                this.RemoveTeacherInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveTeacherInfoOperationCompleted);
            }
            this.InvokeAsync("RemoveTeacherInfo", new object[] {
                        email}, this.RemoveTeacherInfoOperationCompleted, userState);
        }
        
        private void OnRemoveTeacherInfoOperationCompleted(object arg) {
            if ((this.RemoveTeacherInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveTeacherInfoCompleted(this, new RemoveTeacherInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITeacherService/AddComment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddComment([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] TeacherCommentView model, out ReturnState AddCommentResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool AddCommentResultSpecified) {
            object[] results = this.Invoke("AddComment", new object[] {
                        model});
            AddCommentResult = ((ReturnState)(results[0]));
            AddCommentResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void AddCommentAsync(TeacherCommentView model) {
            this.AddCommentAsync(model, null);
        }
        
        /// <remarks/>
        public void AddCommentAsync(TeacherCommentView model, object userState) {
            if ((this.AddCommentOperationCompleted == null)) {
                this.AddCommentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddCommentOperationCompleted);
            }
            this.InvokeAsync("AddComment", new object[] {
                        model}, this.AddCommentOperationCompleted, userState);
        }
        
        private void OnAddCommentOperationCompleted(object arg) {
            if ((this.AddCommentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCommentCompleted(this, new AddCommentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITeacherService/RemoveComment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoveComment([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] TeacherCommentView model, out ReturnState RemoveCommentResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool RemoveCommentResultSpecified) {
            object[] results = this.Invoke("RemoveComment", new object[] {
                        model});
            RemoveCommentResult = ((ReturnState)(results[0]));
            RemoveCommentResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void RemoveCommentAsync(TeacherCommentView model) {
            this.RemoveCommentAsync(model, null);
        }
        
        /// <remarks/>
        public void RemoveCommentAsync(TeacherCommentView model, object userState) {
            if ((this.RemoveCommentOperationCompleted == null)) {
                this.RemoveCommentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveCommentOperationCompleted);
            }
            this.InvokeAsync("RemoveComment", new object[] {
                        model}, this.RemoveCommentOperationCompleted, userState);
        }
        
        private void OnRemoveCommentOperationCompleted(object arg) {
            if ((this.RemoveCommentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveCommentCompleted(this, new RemoveCommentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITeacherService/GetCommentByEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Services.cnts")]
        public TeacherCommentView[] GetCommentByEmail([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email) {
            object[] results = this.Invoke("GetCommentByEmail", new object[] {
                        email});
            return ((TeacherCommentView[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCommentByEmailAsync(string email) {
            this.GetCommentByEmailAsync(email, null);
        }
        
        /// <remarks/>
        public void GetCommentByEmailAsync(string email, object userState) {
            if ((this.GetCommentByEmailOperationCompleted == null)) {
                this.GetCommentByEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCommentByEmailOperationCompleted);
            }
            this.InvokeAsync("GetCommentByEmail", new object[] {
                        email}, this.GetCommentByEmailOperationCompleted, userState);
        }
        
        private void OnGetCommentByEmailOperationCompleted(object arg) {
            if ((this.GetCommentByEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCommentByEmailCompleted(this, new GetCommentByEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITeacherService/GetValidFloor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetValidFloor([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string code, out int GetValidFloorResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool GetValidFloorResultSpecified) {
            object[] results = this.Invoke("GetValidFloor", new object[] {
                        code});
            GetValidFloorResult = ((int)(results[0]));
            GetValidFloorResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void GetValidFloorAsync(string code) {
            this.GetValidFloorAsync(code, null);
        }
        
        /// <remarks/>
        public void GetValidFloorAsync(string code, object userState) {
            if ((this.GetValidFloorOperationCompleted == null)) {
                this.GetValidFloorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetValidFloorOperationCompleted);
            }
            this.InvokeAsync("GetValidFloor", new object[] {
                        code}, this.GetValidFloorOperationCompleted, userState);
        }
        
        private void OnGetValidFloorOperationCompleted(object arg) {
            if ((this.GetValidFloorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetValidFloorCompleted(this, new GetValidFloorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITeacherService/RemoveTeacherComment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoveTeacherComment(int id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idSpecified) {
            this.Invoke("RemoveTeacherComment", new object[] {
                        id,
                        idSpecified});
        }
        
        /// <remarks/>
        public void RemoveTeacherCommentAsync(int id, bool idSpecified) {
            this.RemoveTeacherCommentAsync(id, idSpecified, null);
        }
        
        /// <remarks/>
        public void RemoveTeacherCommentAsync(int id, bool idSpecified, object userState) {
            if ((this.RemoveTeacherCommentOperationCompleted == null)) {
                this.RemoveTeacherCommentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveTeacherCommentOperationCompleted);
            }
            this.InvokeAsync("RemoveTeacherComment", new object[] {
                        id,
                        idSpecified}, this.RemoveTeacherCommentOperationCompleted, userState);
        }
        
        private void OnRemoveTeacherCommentOperationCompleted(object arg) {
            if ((this.RemoveTeacherCommentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveTeacherCommentCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Services.cnts")]
    public partial class TeacherInfoView {
        
        private string despField;
        
        private string emailField;
        
        private int jobTitleField;
        
        private System.DateTime registeDateField;
        
        private bool registeDateFieldSpecified;
        
        private string sexField;
        
        private string telField;
        
        private int universityField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Desp {
            get {
                return this.despField;
            }
            set {
                this.despField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public int JobTitle {
            get {
                return this.jobTitleField;
            }
            set {
                this.jobTitleField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RegisteDate {
            get {
                return this.registeDateField;
            }
            set {
                this.registeDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegisteDateSpecified {
            get {
                return this.registeDateFieldSpecified;
            }
            set {
                this.registeDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Tel {
            get {
                return this.telField;
            }
            set {
                this.telField = value;
            }
        }
        
        /// <remarks/>
        public int University {
            get {
                return this.universityField;
            }
            set {
                this.universityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Services.cnts")]
    public partial class TeacherCommentView {
        
        private string contentField;
        
        private string emailField;
        
        private int floorField;
        
        private bool floorFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private System.DateTime pubDateField;
        
        private bool pubDateFieldSpecified;
        
        private string teacherField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public int Floor {
            get {
                return this.floorField;
            }
            set {
                this.floorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FloorSpecified {
            get {
                return this.floorFieldSpecified;
            }
            set {
                this.floorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PubDate {
            get {
                return this.pubDateField;
            }
            set {
                this.pubDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PubDateSpecified {
            get {
                return this.pubDateFieldSpecified;
            }
            set {
                this.pubDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Teacher {
            get {
                return this.teacherField;
            }
            set {
                this.teacherField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CommonLib")]
    public enum ReturnState {
        
        /// <remarks/>
        ReturnOK,
        
        /// <remarks/>
        ReturnError,
        
        /// <remarks/>
        SystemError,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AddTeacherInfoCompletedEventHandler(object sender, AddTeacherInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddTeacherInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddTeacherInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnState AddTeacherInfoResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnState)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool AddTeacherInfoResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetTeacherInfoCompletedEventHandler(object sender, GetTeacherInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTeacherInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTeacherInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TeacherInfoView Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TeacherInfoView)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void UpdateTeacherrInfoCompletedEventHandler(object sender, UpdateTeacherrInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateTeacherrInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateTeacherrInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnState UpdateTeacherrInfoResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnState)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool UpdateTeacherrInfoResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void HasMemberCompletedEventHandler(object sender, HasMemberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HasMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool HasMemberResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool HasMemberResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetTeacherInfoListCompletedEventHandler(object sender, GetTeacherInfoListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTeacherInfoListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTeacherInfoListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TeacherInfoView[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TeacherInfoView[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void RemoveTeacherInfoCompletedEventHandler(object sender, RemoveTeacherInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveTeacherInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveTeacherInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnState RemoveTeacherInfoResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnState)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool RemoveTeacherInfoResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AddCommentCompletedEventHandler(object sender, AddCommentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddCommentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddCommentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnState AddCommentResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnState)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool AddCommentResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void RemoveCommentCompletedEventHandler(object sender, RemoveCommentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveCommentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveCommentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnState RemoveCommentResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnState)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool RemoveCommentResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetCommentByEmailCompletedEventHandler(object sender, GetCommentByEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCommentByEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCommentByEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TeacherCommentView[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TeacherCommentView[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetValidFloorCompletedEventHandler(object sender, GetValidFloorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetValidFloorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetValidFloorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int GetValidFloorResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool GetValidFloorResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void RemoveTeacherCommentCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591