//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Admin.CourseService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ICourseService", Namespace="http://tempuri.org/")]
    public partial class CourseService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddCourseOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCourseByPageOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddCourseApplyOperationCompleted;
        
        private System.Threading.SendOrPostCallback HasMemberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCourseReviewViewByEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCourseReviewsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReviewPassOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReviewFailedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCourseByCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback DelCourseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CourseService() {
            this.Url = global::Admin.Properties.Settings.Default.Admin_CourseService_CourseService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddCourseCompletedEventHandler AddCourseCompleted;
        
        /// <remarks/>
        public event GetCourseByPageCompletedEventHandler GetCourseByPageCompleted;
        
        /// <remarks/>
        public event AddCourseApplyCompletedEventHandler AddCourseApplyCompleted;
        
        /// <remarks/>
        public event HasMemberCompletedEventHandler HasMemberCompleted;
        
        /// <remarks/>
        public event GetCourseReviewViewByEmailCompletedEventHandler GetCourseReviewViewByEmailCompleted;
        
        /// <remarks/>
        public event GetCourseReviewsCompletedEventHandler GetCourseReviewsCompleted;
        
        /// <remarks/>
        public event ReviewPassCompletedEventHandler ReviewPassCompleted;
        
        /// <remarks/>
        public event ReviewFailedCompletedEventHandler ReviewFailedCompleted;
        
        /// <remarks/>
        public event GetCourseByCodeCompletedEventHandler GetCourseByCodeCompleted;
        
        /// <remarks/>
        public event DelCourseCompletedEventHandler DelCourseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICourseService/AddCourse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddCourse([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CourseView model, out ReturnState AddCourseResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool AddCourseResultSpecified) {
            object[] results = this.Invoke("AddCourse", new object[] {
                        model});
            AddCourseResult = ((ReturnState)(results[0]));
            AddCourseResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void AddCourseAsync(CourseView model) {
            this.AddCourseAsync(model, null);
        }
        
        /// <remarks/>
        public void AddCourseAsync(CourseView model, object userState) {
            if ((this.AddCourseOperationCompleted == null)) {
                this.AddCourseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddCourseOperationCompleted);
            }
            this.InvokeAsync("AddCourse", new object[] {
                        model}, this.AddCourseOperationCompleted, userState);
        }
        
        private void OnAddCourseOperationCompleted(object arg) {
            if ((this.AddCourseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCourseCompleted(this, new AddCourseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICourseService/GetCourseByPage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Services.cnts")]
        public CourseView[] GetCourseByPage(int page, [System.Xml.Serialization.XmlIgnoreAttribute()] bool pageSpecified, int nPage, [System.Xml.Serialization.XmlIgnoreAttribute()] bool nPageSpecified) {
            object[] results = this.Invoke("GetCourseByPage", new object[] {
                        page,
                        pageSpecified,
                        nPage,
                        nPageSpecified});
            return ((CourseView[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCourseByPageAsync(int page, bool pageSpecified, int nPage, bool nPageSpecified) {
            this.GetCourseByPageAsync(page, pageSpecified, nPage, nPageSpecified, null);
        }
        
        /// <remarks/>
        public void GetCourseByPageAsync(int page, bool pageSpecified, int nPage, bool nPageSpecified, object userState) {
            if ((this.GetCourseByPageOperationCompleted == null)) {
                this.GetCourseByPageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCourseByPageOperationCompleted);
            }
            this.InvokeAsync("GetCourseByPage", new object[] {
                        page,
                        pageSpecified,
                        nPage,
                        nPageSpecified}, this.GetCourseByPageOperationCompleted, userState);
        }
        
        private void OnGetCourseByPageOperationCompleted(object arg) {
            if ((this.GetCourseByPageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCourseByPageCompleted(this, new GetCourseByPageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICourseService/AddCourseApply", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddCourseApply([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CourseView model, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] UserApply user, out ReturnState AddCourseApplyResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool AddCourseApplyResultSpecified) {
            object[] results = this.Invoke("AddCourseApply", new object[] {
                        model,
                        user});
            AddCourseApplyResult = ((ReturnState)(results[0]));
            AddCourseApplyResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void AddCourseApplyAsync(CourseView model, UserApply user) {
            this.AddCourseApplyAsync(model, user, null);
        }
        
        /// <remarks/>
        public void AddCourseApplyAsync(CourseView model, UserApply user, object userState) {
            if ((this.AddCourseApplyOperationCompleted == null)) {
                this.AddCourseApplyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddCourseApplyOperationCompleted);
            }
            this.InvokeAsync("AddCourseApply", new object[] {
                        model,
                        user}, this.AddCourseApplyOperationCompleted, userState);
        }
        
        private void OnAddCourseApplyOperationCompleted(object arg) {
            if ((this.AddCourseApplyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCourseApplyCompleted(this, new AddCourseApplyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICourseService/HasMember", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void HasMember([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string code, out bool HasMemberResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool HasMemberResultSpecified) {
            object[] results = this.Invoke("HasMember", new object[] {
                        code});
            HasMemberResult = ((bool)(results[0]));
            HasMemberResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void HasMemberAsync(string code) {
            this.HasMemberAsync(code, null);
        }
        
        /// <remarks/>
        public void HasMemberAsync(string code, object userState) {
            if ((this.HasMemberOperationCompleted == null)) {
                this.HasMemberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHasMemberOperationCompleted);
            }
            this.InvokeAsync("HasMember", new object[] {
                        code}, this.HasMemberOperationCompleted, userState);
        }
        
        private void OnHasMemberOperationCompleted(object arg) {
            if ((this.HasMemberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HasMemberCompleted(this, new HasMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICourseService/GetCourseReviewViewByEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Services.cnts")]
        public CourseReviewView[] GetCourseReviewViewByEmail([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email) {
            object[] results = this.Invoke("GetCourseReviewViewByEmail", new object[] {
                        email});
            return ((CourseReviewView[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCourseReviewViewByEmailAsync(string email) {
            this.GetCourseReviewViewByEmailAsync(email, null);
        }
        
        /// <remarks/>
        public void GetCourseReviewViewByEmailAsync(string email, object userState) {
            if ((this.GetCourseReviewViewByEmailOperationCompleted == null)) {
                this.GetCourseReviewViewByEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCourseReviewViewByEmailOperationCompleted);
            }
            this.InvokeAsync("GetCourseReviewViewByEmail", new object[] {
                        email}, this.GetCourseReviewViewByEmailOperationCompleted, userState);
        }
        
        private void OnGetCourseReviewViewByEmailOperationCompleted(object arg) {
            if ((this.GetCourseReviewViewByEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCourseReviewViewByEmailCompleted(this, new GetCourseReviewViewByEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICourseService/GetCourseReviews", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Services.cnts")]
        public CourseReviewView[] GetCourseReviews() {
            object[] results = this.Invoke("GetCourseReviews", new object[0]);
            return ((CourseReviewView[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCourseReviewsAsync() {
            this.GetCourseReviewsAsync(null);
        }
        
        /// <remarks/>
        public void GetCourseReviewsAsync(object userState) {
            if ((this.GetCourseReviewsOperationCompleted == null)) {
                this.GetCourseReviewsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCourseReviewsOperationCompleted);
            }
            this.InvokeAsync("GetCourseReviews", new object[0], this.GetCourseReviewsOperationCompleted, userState);
        }
        
        private void OnGetCourseReviewsOperationCompleted(object arg) {
            if ((this.GetCourseReviewsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCourseReviewsCompleted(this, new GetCourseReviewsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICourseService/ReviewPass", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ReviewPass([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string code, out ReturnState ReviewPassResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ReviewPassResultSpecified) {
            object[] results = this.Invoke("ReviewPass", new object[] {
                        code});
            ReviewPassResult = ((ReturnState)(results[0]));
            ReviewPassResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void ReviewPassAsync(string code) {
            this.ReviewPassAsync(code, null);
        }
        
        /// <remarks/>
        public void ReviewPassAsync(string code, object userState) {
            if ((this.ReviewPassOperationCompleted == null)) {
                this.ReviewPassOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReviewPassOperationCompleted);
            }
            this.InvokeAsync("ReviewPass", new object[] {
                        code}, this.ReviewPassOperationCompleted, userState);
        }
        
        private void OnReviewPassOperationCompleted(object arg) {
            if ((this.ReviewPassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReviewPassCompleted(this, new ReviewPassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICourseService/ReviewFailed", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ReviewFailed([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string code, out ReturnState ReviewFailedResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ReviewFailedResultSpecified) {
            object[] results = this.Invoke("ReviewFailed", new object[] {
                        code});
            ReviewFailedResult = ((ReturnState)(results[0]));
            ReviewFailedResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void ReviewFailedAsync(string code) {
            this.ReviewFailedAsync(code, null);
        }
        
        /// <remarks/>
        public void ReviewFailedAsync(string code, object userState) {
            if ((this.ReviewFailedOperationCompleted == null)) {
                this.ReviewFailedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReviewFailedOperationCompleted);
            }
            this.InvokeAsync("ReviewFailed", new object[] {
                        code}, this.ReviewFailedOperationCompleted, userState);
        }
        
        private void OnReviewFailedOperationCompleted(object arg) {
            if ((this.ReviewFailedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReviewFailedCompleted(this, new ReviewFailedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICourseService/GetCourseByCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CourseView GetCourseByCode([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string code) {
            object[] results = this.Invoke("GetCourseByCode", new object[] {
                        code});
            return ((CourseView)(results[0]));
        }
        
        /// <remarks/>
        public void GetCourseByCodeAsync(string code) {
            this.GetCourseByCodeAsync(code, null);
        }
        
        /// <remarks/>
        public void GetCourseByCodeAsync(string code, object userState) {
            if ((this.GetCourseByCodeOperationCompleted == null)) {
                this.GetCourseByCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCourseByCodeOperationCompleted);
            }
            this.InvokeAsync("GetCourseByCode", new object[] {
                        code}, this.GetCourseByCodeOperationCompleted, userState);
        }
        
        private void OnGetCourseByCodeOperationCompleted(object arg) {
            if ((this.GetCourseByCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCourseByCodeCompleted(this, new GetCourseByCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICourseService/DelCourse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DelCourse([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string code) {
            this.Invoke("DelCourse", new object[] {
                        code});
        }
        
        /// <remarks/>
        public void DelCourseAsync(string code) {
            this.DelCourseAsync(code, null);
        }
        
        /// <remarks/>
        public void DelCourseAsync(string code, object userState) {
            if ((this.DelCourseOperationCompleted == null)) {
                this.DelCourseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelCourseOperationCompleted);
            }
            this.InvokeAsync("DelCourse", new object[] {
                        code}, this.DelCourseOperationCompleted, userState);
        }
        
        private void OnDelCourseOperationCompleted(object arg) {
            if ((this.DelCourseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DelCourseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Services.cnts")]
    public partial class CourseView {
        
        private string codeField;
        
        private string despField;
        
        private string nameField;
        
        private string picUrlField;
        
        private int universityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Desp {
            get {
                return this.despField;
            }
            set {
                this.despField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PicUrl {
            get {
                return this.picUrlField;
            }
            set {
                this.picUrlField = value;
            }
        }
        
        /// <remarks/>
        public int University {
            get {
                return this.universityField;
            }
            set {
                this.universityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Services.cnts")]
    public partial class CourseReviewView {
        
        private string codeField;
        
        private System.DateTime commitDateField;
        
        private bool commitDateFieldSpecified;
        
        private string despField;
        
        private string emailField;
        
        private string nameField;
        
        private string picUrlField;
        
        private string statusField;
        
        private string universityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CommitDate {
            get {
                return this.commitDateField;
            }
            set {
                this.commitDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CommitDateSpecified {
            get {
                return this.commitDateFieldSpecified;
            }
            set {
                this.commitDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Desp {
            get {
                return this.despField;
            }
            set {
                this.despField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PicUrl {
            get {
                return this.picUrlField;
            }
            set {
                this.picUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string University {
            get {
                return this.universityField;
            }
            set {
                this.universityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Services.cnts")]
    public partial class UserApply {
        
        private System.DateTime commitDateField;
        
        private bool commitDateFieldSpecified;
        
        private string emailField;
        
        private int statusField;
        
        /// <remarks/>
        public System.DateTime CommitDate {
            get {
                return this.commitDateField;
            }
            set {
                this.commitDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CommitDateSpecified {
            get {
                return this.commitDateFieldSpecified;
            }
            set {
                this.commitDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CommonLib")]
    public enum ReturnState {
        
        /// <remarks/>
        ReturnOK,
        
        /// <remarks/>
        ReturnError,
        
        /// <remarks/>
        SystemError,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AddCourseCompletedEventHandler(object sender, AddCourseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddCourseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddCourseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnState AddCourseResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnState)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool AddCourseResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetCourseByPageCompletedEventHandler(object sender, GetCourseByPageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCourseByPageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCourseByPageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CourseView[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CourseView[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AddCourseApplyCompletedEventHandler(object sender, AddCourseApplyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddCourseApplyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddCourseApplyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnState AddCourseApplyResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnState)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool AddCourseApplyResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void HasMemberCompletedEventHandler(object sender, HasMemberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HasMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool HasMemberResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool HasMemberResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetCourseReviewViewByEmailCompletedEventHandler(object sender, GetCourseReviewViewByEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCourseReviewViewByEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCourseReviewViewByEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CourseReviewView[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CourseReviewView[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetCourseReviewsCompletedEventHandler(object sender, GetCourseReviewsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCourseReviewsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCourseReviewsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CourseReviewView[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CourseReviewView[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ReviewPassCompletedEventHandler(object sender, ReviewPassCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReviewPassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReviewPassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnState ReviewPassResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnState)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool ReviewPassResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ReviewFailedCompletedEventHandler(object sender, ReviewFailedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReviewFailedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReviewFailedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnState ReviewFailedResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnState)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool ReviewFailedResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetCourseByCodeCompletedEventHandler(object sender, GetCourseByCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCourseByCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCourseByCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CourseView Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CourseView)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void DelCourseCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591