//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Admin.CourseCommentService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ICourseCommentService", Namespace="http://tempuri.org/")]
    public partial class CourseCommentService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddCommentOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveCommentOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveCommentByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCommentByCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetValidFloorOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CourseCommentService() {
            this.Url = global::Admin.Properties.Settings.Default.Admin_CourseCommentService_CourseCommentService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddCommentCompletedEventHandler AddCommentCompleted;
        
        /// <remarks/>
        public event RemoveCommentCompletedEventHandler RemoveCommentCompleted;
        
        /// <remarks/>
        public event RemoveCommentByIdCompletedEventHandler RemoveCommentByIdCompleted;
        
        /// <remarks/>
        public event GetCommentByCodeCompletedEventHandler GetCommentByCodeCompleted;
        
        /// <remarks/>
        public event GetValidFloorCompletedEventHandler GetValidFloorCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICourseCommentService/AddComment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddComment([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CourseCommentView model, out ReturnState AddCommentResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool AddCommentResultSpecified) {
            object[] results = this.Invoke("AddComment", new object[] {
                        model});
            AddCommentResult = ((ReturnState)(results[0]));
            AddCommentResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void AddCommentAsync(CourseCommentView model) {
            this.AddCommentAsync(model, null);
        }
        
        /// <remarks/>
        public void AddCommentAsync(CourseCommentView model, object userState) {
            if ((this.AddCommentOperationCompleted == null)) {
                this.AddCommentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddCommentOperationCompleted);
            }
            this.InvokeAsync("AddComment", new object[] {
                        model}, this.AddCommentOperationCompleted, userState);
        }
        
        private void OnAddCommentOperationCompleted(object arg) {
            if ((this.AddCommentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCommentCompleted(this, new AddCommentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICourseCommentService/RemoveComment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoveComment([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CourseCommentView model, out ReturnState RemoveCommentResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool RemoveCommentResultSpecified) {
            object[] results = this.Invoke("RemoveComment", new object[] {
                        model});
            RemoveCommentResult = ((ReturnState)(results[0]));
            RemoveCommentResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void RemoveCommentAsync(CourseCommentView model) {
            this.RemoveCommentAsync(model, null);
        }
        
        /// <remarks/>
        public void RemoveCommentAsync(CourseCommentView model, object userState) {
            if ((this.RemoveCommentOperationCompleted == null)) {
                this.RemoveCommentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveCommentOperationCompleted);
            }
            this.InvokeAsync("RemoveComment", new object[] {
                        model}, this.RemoveCommentOperationCompleted, userState);
        }
        
        private void OnRemoveCommentOperationCompleted(object arg) {
            if ((this.RemoveCommentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveCommentCompleted(this, new RemoveCommentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICourseCommentService/RemoveCommentById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoveCommentById(int id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idSpecified, out ReturnState RemoveCommentByIdResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool RemoveCommentByIdResultSpecified) {
            object[] results = this.Invoke("RemoveCommentById", new object[] {
                        id,
                        idSpecified});
            RemoveCommentByIdResult = ((ReturnState)(results[0]));
            RemoveCommentByIdResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void RemoveCommentByIdAsync(int id, bool idSpecified) {
            this.RemoveCommentByIdAsync(id, idSpecified, null);
        }
        
        /// <remarks/>
        public void RemoveCommentByIdAsync(int id, bool idSpecified, object userState) {
            if ((this.RemoveCommentByIdOperationCompleted == null)) {
                this.RemoveCommentByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveCommentByIdOperationCompleted);
            }
            this.InvokeAsync("RemoveCommentById", new object[] {
                        id,
                        idSpecified}, this.RemoveCommentByIdOperationCompleted, userState);
        }
        
        private void OnRemoveCommentByIdOperationCompleted(object arg) {
            if ((this.RemoveCommentByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveCommentByIdCompleted(this, new RemoveCommentByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICourseCommentService/GetCommentByCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Services.cnts")]
        public CourseCommentView[] GetCommentByCode([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string code) {
            object[] results = this.Invoke("GetCommentByCode", new object[] {
                        code});
            return ((CourseCommentView[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCommentByCodeAsync(string code) {
            this.GetCommentByCodeAsync(code, null);
        }
        
        /// <remarks/>
        public void GetCommentByCodeAsync(string code, object userState) {
            if ((this.GetCommentByCodeOperationCompleted == null)) {
                this.GetCommentByCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCommentByCodeOperationCompleted);
            }
            this.InvokeAsync("GetCommentByCode", new object[] {
                        code}, this.GetCommentByCodeOperationCompleted, userState);
        }
        
        private void OnGetCommentByCodeOperationCompleted(object arg) {
            if ((this.GetCommentByCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCommentByCodeCompleted(this, new GetCommentByCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICourseCommentService/GetValidFloor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetValidFloor([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string code, out int GetValidFloorResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool GetValidFloorResultSpecified) {
            object[] results = this.Invoke("GetValidFloor", new object[] {
                        code});
            GetValidFloorResult = ((int)(results[0]));
            GetValidFloorResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void GetValidFloorAsync(string code) {
            this.GetValidFloorAsync(code, null);
        }
        
        /// <remarks/>
        public void GetValidFloorAsync(string code, object userState) {
            if ((this.GetValidFloorOperationCompleted == null)) {
                this.GetValidFloorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetValidFloorOperationCompleted);
            }
            this.InvokeAsync("GetValidFloor", new object[] {
                        code}, this.GetValidFloorOperationCompleted, userState);
        }
        
        private void OnGetValidFloorOperationCompleted(object arg) {
            if ((this.GetValidFloorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetValidFloorCompleted(this, new GetValidFloorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Services.cnts")]
    public partial class CourseCommentView {
        
        private string codeField;
        
        private string contentField;
        
        private string emailField;
        
        private int floorField;
        
        private int idField;
        
        private System.DateTime pubDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public int Floor {
            get {
                return this.floorField;
            }
            set {
                this.floorField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PubDate {
            get {
                return this.pubDateField;
            }
            set {
                this.pubDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CommonLib")]
    public enum ReturnState {
        
        /// <remarks/>
        ReturnOK,
        
        /// <remarks/>
        ReturnError,
        
        /// <remarks/>
        SystemError,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AddCommentCompletedEventHandler(object sender, AddCommentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddCommentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddCommentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnState AddCommentResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnState)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool AddCommentResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void RemoveCommentCompletedEventHandler(object sender, RemoveCommentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveCommentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveCommentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnState RemoveCommentResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnState)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool RemoveCommentResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void RemoveCommentByIdCompletedEventHandler(object sender, RemoveCommentByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveCommentByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveCommentByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnState RemoveCommentByIdResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnState)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool RemoveCommentByIdResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetCommentByCodeCompletedEventHandler(object sender, GetCommentByCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCommentByCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCommentByCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CourseCommentView[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CourseCommentView[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetValidFloorCompletedEventHandler(object sender, GetValidFloorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetValidFloorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetValidFloorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int GetValidFloorResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool GetValidFloorResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591