//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCViews.TeacherService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeacherInfoView", Namespace="http://schemas.datacontract.org/2004/07/Services.cnts")]
    [System.SerializableAttribute()]
    public partial class TeacherInfoView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DespField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JobTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegisteDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UniversityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Desp {
            get {
                return this.DespField;
            }
            set {
                if ((object.ReferenceEquals(this.DespField, value) != true)) {
                    this.DespField = value;
                    this.RaisePropertyChanged("Desp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JobTitle {
            get {
                return this.JobTitleField;
            }
            set {
                if ((this.JobTitleField.Equals(value) != true)) {
                    this.JobTitleField = value;
                    this.RaisePropertyChanged("JobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegisteDate {
            get {
                return this.RegisteDateField;
            }
            set {
                if ((this.RegisteDateField.Equals(value) != true)) {
                    this.RegisteDateField = value;
                    this.RaisePropertyChanged("RegisteDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel {
            get {
                return this.TelField;
            }
            set {
                if ((object.ReferenceEquals(this.TelField, value) != true)) {
                    this.TelField = value;
                    this.RaisePropertyChanged("Tel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int University {
            get {
                return this.UniversityField;
            }
            set {
                if ((this.UniversityField.Equals(value) != true)) {
                    this.UniversityField = value;
                    this.RaisePropertyChanged("University");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeacherCommentView", Namespace="http://schemas.datacontract.org/2004/07/Services.cnts")]
    [System.SerializableAttribute()]
    public partial class TeacherCommentView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FloorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PubDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Floor {
            get {
                return this.FloorField;
            }
            set {
                if ((this.FloorField.Equals(value) != true)) {
                    this.FloorField = value;
                    this.RaisePropertyChanged("Floor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PubDate {
            get {
                return this.PubDateField;
            }
            set {
                if ((this.PubDateField.Equals(value) != true)) {
                    this.PubDateField = value;
                    this.RaisePropertyChanged("PubDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Teacher {
            get {
                return this.TeacherField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherField, value) != true)) {
                    this.TeacherField = value;
                    this.RaisePropertyChanged("Teacher");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TeacherService.ITeacherService")]
    public interface ITeacherService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/AddTeacherInfo", ReplyAction="http://tempuri.org/ITeacherService/AddTeacherInfoResponse")]
        CommonLib.ReturnState AddTeacherInfo(MVCViews.TeacherService.TeacherInfoView model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/AddTeacherInfo", ReplyAction="http://tempuri.org/ITeacherService/AddTeacherInfoResponse")]
        System.Threading.Tasks.Task<CommonLib.ReturnState> AddTeacherInfoAsync(MVCViews.TeacherService.TeacherInfoView model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/GetTeacherInfo", ReplyAction="http://tempuri.org/ITeacherService/GetTeacherInfoResponse")]
        MVCViews.TeacherService.TeacherInfoView GetTeacherInfo(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/GetTeacherInfo", ReplyAction="http://tempuri.org/ITeacherService/GetTeacherInfoResponse")]
        System.Threading.Tasks.Task<MVCViews.TeacherService.TeacherInfoView> GetTeacherInfoAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/UpdateTeacherrInfo", ReplyAction="http://tempuri.org/ITeacherService/UpdateTeacherrInfoResponse")]
        CommonLib.ReturnState UpdateTeacherrInfo(MVCViews.TeacherService.TeacherInfoView model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/UpdateTeacherrInfo", ReplyAction="http://tempuri.org/ITeacherService/UpdateTeacherrInfoResponse")]
        System.Threading.Tasks.Task<CommonLib.ReturnState> UpdateTeacherrInfoAsync(MVCViews.TeacherService.TeacherInfoView model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/HasMember", ReplyAction="http://tempuri.org/ITeacherService/HasMemberResponse")]
        bool HasMember(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/HasMember", ReplyAction="http://tempuri.org/ITeacherService/HasMemberResponse")]
        System.Threading.Tasks.Task<bool> HasMemberAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/GetTeacherInfoList", ReplyAction="http://tempuri.org/ITeacherService/GetTeacherInfoListResponse")]
        MVCViews.TeacherService.TeacherInfoView[] GetTeacherInfoList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/GetTeacherInfoList", ReplyAction="http://tempuri.org/ITeacherService/GetTeacherInfoListResponse")]
        System.Threading.Tasks.Task<MVCViews.TeacherService.TeacherInfoView[]> GetTeacherInfoListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/RemoveTeacherInfo", ReplyAction="http://tempuri.org/ITeacherService/RemoveTeacherInfoResponse")]
        CommonLib.ReturnState RemoveTeacherInfo(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/RemoveTeacherInfo", ReplyAction="http://tempuri.org/ITeacherService/RemoveTeacherInfoResponse")]
        System.Threading.Tasks.Task<CommonLib.ReturnState> RemoveTeacherInfoAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/AddComment", ReplyAction="http://tempuri.org/ITeacherService/AddCommentResponse")]
        CommonLib.ReturnState AddComment(MVCViews.TeacherService.TeacherCommentView model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/AddComment", ReplyAction="http://tempuri.org/ITeacherService/AddCommentResponse")]
        System.Threading.Tasks.Task<CommonLib.ReturnState> AddCommentAsync(MVCViews.TeacherService.TeacherCommentView model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/RemoveComment", ReplyAction="http://tempuri.org/ITeacherService/RemoveCommentResponse")]
        CommonLib.ReturnState RemoveComment(MVCViews.TeacherService.TeacherCommentView model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/RemoveComment", ReplyAction="http://tempuri.org/ITeacherService/RemoveCommentResponse")]
        System.Threading.Tasks.Task<CommonLib.ReturnState> RemoveCommentAsync(MVCViews.TeacherService.TeacherCommentView model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/GetCommentByEmail", ReplyAction="http://tempuri.org/ITeacherService/GetCommentByEmailResponse")]
        MVCViews.TeacherService.TeacherCommentView[] GetCommentByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/GetCommentByEmail", ReplyAction="http://tempuri.org/ITeacherService/GetCommentByEmailResponse")]
        System.Threading.Tasks.Task<MVCViews.TeacherService.TeacherCommentView[]> GetCommentByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/GetValidFloor", ReplyAction="http://tempuri.org/ITeacherService/GetValidFloorResponse")]
        int GetValidFloor(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/GetValidFloor", ReplyAction="http://tempuri.org/ITeacherService/GetValidFloorResponse")]
        System.Threading.Tasks.Task<int> GetValidFloorAsync(string code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITeacherServiceChannel : MVCViews.TeacherService.ITeacherService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TeacherServiceClient : System.ServiceModel.ClientBase<MVCViews.TeacherService.ITeacherService>, MVCViews.TeacherService.ITeacherService {
        
        public TeacherServiceClient() {
        }
        
        public TeacherServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TeacherServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeacherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeacherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CommonLib.ReturnState AddTeacherInfo(MVCViews.TeacherService.TeacherInfoView model) {
            return base.Channel.AddTeacherInfo(model);
        }
        
        public System.Threading.Tasks.Task<CommonLib.ReturnState> AddTeacherInfoAsync(MVCViews.TeacherService.TeacherInfoView model) {
            return base.Channel.AddTeacherInfoAsync(model);
        }
        
        public MVCViews.TeacherService.TeacherInfoView GetTeacherInfo(string email) {
            return base.Channel.GetTeacherInfo(email);
        }
        
        public System.Threading.Tasks.Task<MVCViews.TeacherService.TeacherInfoView> GetTeacherInfoAsync(string email) {
            return base.Channel.GetTeacherInfoAsync(email);
        }
        
        public CommonLib.ReturnState UpdateTeacherrInfo(MVCViews.TeacherService.TeacherInfoView model) {
            return base.Channel.UpdateTeacherrInfo(model);
        }
        
        public System.Threading.Tasks.Task<CommonLib.ReturnState> UpdateTeacherrInfoAsync(MVCViews.TeacherService.TeacherInfoView model) {
            return base.Channel.UpdateTeacherrInfoAsync(model);
        }
        
        public bool HasMember(string email) {
            return base.Channel.HasMember(email);
        }
        
        public System.Threading.Tasks.Task<bool> HasMemberAsync(string email) {
            return base.Channel.HasMemberAsync(email);
        }
        
        public MVCViews.TeacherService.TeacherInfoView[] GetTeacherInfoList() {
            return base.Channel.GetTeacherInfoList();
        }
        
        public System.Threading.Tasks.Task<MVCViews.TeacherService.TeacherInfoView[]> GetTeacherInfoListAsync() {
            return base.Channel.GetTeacherInfoListAsync();
        }
        
        public CommonLib.ReturnState RemoveTeacherInfo(string email) {
            return base.Channel.RemoveTeacherInfo(email);
        }
        
        public System.Threading.Tasks.Task<CommonLib.ReturnState> RemoveTeacherInfoAsync(string email) {
            return base.Channel.RemoveTeacherInfoAsync(email);
        }
        
        public CommonLib.ReturnState AddComment(MVCViews.TeacherService.TeacherCommentView model) {
            return base.Channel.AddComment(model);
        }
        
        public System.Threading.Tasks.Task<CommonLib.ReturnState> AddCommentAsync(MVCViews.TeacherService.TeacherCommentView model) {
            return base.Channel.AddCommentAsync(model);
        }
        
        public CommonLib.ReturnState RemoveComment(MVCViews.TeacherService.TeacherCommentView model) {
            return base.Channel.RemoveComment(model);
        }
        
        public System.Threading.Tasks.Task<CommonLib.ReturnState> RemoveCommentAsync(MVCViews.TeacherService.TeacherCommentView model) {
            return base.Channel.RemoveCommentAsync(model);
        }
        
        public MVCViews.TeacherService.TeacherCommentView[] GetCommentByEmail(string email) {
            return base.Channel.GetCommentByEmail(email);
        }
        
        public System.Threading.Tasks.Task<MVCViews.TeacherService.TeacherCommentView[]> GetCommentByEmailAsync(string email) {
            return base.Channel.GetCommentByEmailAsync(email);
        }
        
        public int GetValidFloor(string code) {
            return base.Channel.GetValidFloor(code);
        }
        
        public System.Threading.Tasks.Task<int> GetValidFloorAsync(string code) {
            return base.Channel.GetValidFloorAsync(code);
        }
    }
}
