//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCViews.CourseCommentServiceDebug {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CourseCommentView", Namespace="http://schemas.datacontract.org/2004/07/Services.cnts")]
    [System.SerializableAttribute()]
    public partial class CourseCommentView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FloorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PubDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Floor {
            get {
                return this.FloorField;
            }
            set {
                if ((this.FloorField.Equals(value) != true)) {
                    this.FloorField = value;
                    this.RaisePropertyChanged("Floor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PubDate {
            get {
                return this.PubDateField;
            }
            set {
                if ((this.PubDateField.Equals(value) != true)) {
                    this.PubDateField = value;
                    this.RaisePropertyChanged("PubDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CourseCommentServiceDebug.ICourseCommentService")]
    public interface ICourseCommentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseCommentService/AddComment", ReplyAction="http://tempuri.org/ICourseCommentService/AddCommentResponse")]
        CommonLib.ReturnState AddComment(MVCViews.CourseCommentServiceDebug.CourseCommentView model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseCommentService/AddComment", ReplyAction="http://tempuri.org/ICourseCommentService/AddCommentResponse")]
        System.Threading.Tasks.Task<CommonLib.ReturnState> AddCommentAsync(MVCViews.CourseCommentServiceDebug.CourseCommentView model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseCommentService/RemoveComment", ReplyAction="http://tempuri.org/ICourseCommentService/RemoveCommentResponse")]
        CommonLib.ReturnState RemoveComment(MVCViews.CourseCommentServiceDebug.CourseCommentView model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseCommentService/RemoveComment", ReplyAction="http://tempuri.org/ICourseCommentService/RemoveCommentResponse")]
        System.Threading.Tasks.Task<CommonLib.ReturnState> RemoveCommentAsync(MVCViews.CourseCommentServiceDebug.CourseCommentView model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseCommentService/RemoveCommentById", ReplyAction="http://tempuri.org/ICourseCommentService/RemoveCommentByIdResponse")]
        CommonLib.ReturnState RemoveCommentById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseCommentService/RemoveCommentById", ReplyAction="http://tempuri.org/ICourseCommentService/RemoveCommentByIdResponse")]
        System.Threading.Tasks.Task<CommonLib.ReturnState> RemoveCommentByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseCommentService/GetCommentByCode", ReplyAction="http://tempuri.org/ICourseCommentService/GetCommentByCodeResponse")]
        MVCViews.CourseCommentServiceDebug.CourseCommentView[] GetCommentByCode(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseCommentService/GetCommentByCode", ReplyAction="http://tempuri.org/ICourseCommentService/GetCommentByCodeResponse")]
        System.Threading.Tasks.Task<MVCViews.CourseCommentServiceDebug.CourseCommentView[]> GetCommentByCodeAsync(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseCommentService/GetValidFloor", ReplyAction="http://tempuri.org/ICourseCommentService/GetValidFloorResponse")]
        int GetValidFloor(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseCommentService/GetValidFloor", ReplyAction="http://tempuri.org/ICourseCommentService/GetValidFloorResponse")]
        System.Threading.Tasks.Task<int> GetValidFloorAsync(string code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICourseCommentServiceChannel : MVCViews.CourseCommentServiceDebug.ICourseCommentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CourseCommentServiceClient : System.ServiceModel.ClientBase<MVCViews.CourseCommentServiceDebug.ICourseCommentService>, MVCViews.CourseCommentServiceDebug.ICourseCommentService {
        
        public CourseCommentServiceClient() {
        }
        
        public CourseCommentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CourseCommentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseCommentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseCommentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CommonLib.ReturnState AddComment(MVCViews.CourseCommentServiceDebug.CourseCommentView model) {
            return base.Channel.AddComment(model);
        }
        
        public System.Threading.Tasks.Task<CommonLib.ReturnState> AddCommentAsync(MVCViews.CourseCommentServiceDebug.CourseCommentView model) {
            return base.Channel.AddCommentAsync(model);
        }
        
        public CommonLib.ReturnState RemoveComment(MVCViews.CourseCommentServiceDebug.CourseCommentView model) {
            return base.Channel.RemoveComment(model);
        }
        
        public System.Threading.Tasks.Task<CommonLib.ReturnState> RemoveCommentAsync(MVCViews.CourseCommentServiceDebug.CourseCommentView model) {
            return base.Channel.RemoveCommentAsync(model);
        }
        
        public CommonLib.ReturnState RemoveCommentById(int id) {
            return base.Channel.RemoveCommentById(id);
        }
        
        public System.Threading.Tasks.Task<CommonLib.ReturnState> RemoveCommentByIdAsync(int id) {
            return base.Channel.RemoveCommentByIdAsync(id);
        }
        
        public MVCViews.CourseCommentServiceDebug.CourseCommentView[] GetCommentByCode(string code) {
            return base.Channel.GetCommentByCode(code);
        }
        
        public System.Threading.Tasks.Task<MVCViews.CourseCommentServiceDebug.CourseCommentView[]> GetCommentByCodeAsync(string code) {
            return base.Channel.GetCommentByCodeAsync(code);
        }
        
        public int GetValidFloor(string code) {
            return base.Channel.GetValidFloor(code);
        }
        
        public System.Threading.Tasks.Task<int> GetValidFloorAsync(string code) {
            return base.Channel.GetValidFloorAsync(code);
        }
    }
}
